[package]
name = "numpy"
version = "0.7.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>", "Yuji Kanagawa <yuji.kngw.80s.revive@gmail.com>"]
description = "Rust binding of NumPy C-API"
documentation = "https://rust-numpy.github.io/rust-numpy/numpy"
edition = "2018"
repository = "https://github.com/rust-numpy/rust-numpy"
keywords = ["numpy", "python", "binding"]
license-file = "LICENSE"

[dependencies]
cfg-if = "0.1"
libc = "0.2"
num-complex = "0.2"
num-traits = "0.2"
ndarray = ">=0.13"
pyo3 = { git = "https://github.com/kngwyu/pyo3.git", branch = "pyclass-new-layout" }
# pyo3 = "0.8"

[features]
# In default setting, python version is automatically detected
default = []
# This is no longer needed but setuptools-rust assumes this feature
python3 = ["pyo3/python3"]

